t=(11,122,13,14,15,116,17,11,19,26)
print("tuple values",t)
print("type :",type (t))
print("minimum value",min(t))
print("maximum value",max(t))
print("length  of the tuple",len(t))
print("count of the number 11 in the tuple ",t.count(11))
print("first index in the tuple",t.index(11))
print("3rd position of the tuple is",t[3])
print("4th position of the tuple is",t[4])
ts=sorted(t)
print("sorted tuple in  the list form",ts)
print("ts type",type(ts))
ts=sorted(t,reverse=True)
print("reverse sorted tuple",ts)
tm=t*2
print("tuple multiplication",tm)